# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-06-02 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200602_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv_file',
            name='session_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
