# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-06-03 12:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200602_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv_file',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
